Reorganizes github actions and disables latex

diff --git a/.github/workflows/check-pull-request.yml b/.github/workflows/check-pull-request.yml
--- a/.github/workflows/check-pull-request.yml
+++ b/.github/workflows/check-pull-request.yml
@@ -27,17 +27,7 @@ jobs:
 
       # Comment warnings onto pull request for easy viewing and feedback.
 
-      # Actions modified from https://github.com/peter-evans/create-or-update-comment
-      - name: Find Editable Comment
-        if: success() || failure() # Run commenting steps even if above steps fails
-        uses: peter-evans/find-comment@v2
-        id: fc
-        with:
-          issue-number: ${{ github.event.pull_request.number }}
-          comment-author: 'github-actions[bot]'
-          body-includes: "Doxygen warnings output: (if empty, there are no warnings). Please correct all warnings before merging."
-
-      # Get file contents as GITHUB_OUTPUT to be used in comment body. Can't simply use body-path since I want to support editing the existing comment.
+      # Get file contents of docs/doxygen_warnings.txt as GITHUB_OUTPUT to be used in comment body. Can't simply use body-path since I want to support editing the existing comment.
       - name: Get File Contents
         if: success() || failure() # Run commenting steps even if above steps fails
         id: doxygen-warnings
@@ -52,6 +42,16 @@ jobs:
           echo "$(cat docs/doxygen_warnings.txt)" >> $GITHUB_OUTPUT
           echo "$EOF" >> $GITHUB_OUTPUT
 
+      # Actions modified from https://github.com/peter-evans/create-or-update-comment
+      - name: Find Editable Comment
+        if: success() || failure() # Run commenting steps even if above steps fails
+        uses: peter-evans/find-comment@v2
+        id: fc
+        with:
+          issue-number: ${{ github.event.pull_request.number }}
+          comment-author: 'github-actions[bot]'
+          body-includes: "Doxygen warnings output: (if empty, there are no warnings). Please correct any warnings before merging."
+        
       # Create or update/edit comment containing build warnings
       - name: Create or update comment
         if: success() || failure() # Run commenting steps even if above steps fails
@@ -60,7 +60,7 @@ jobs:
           comment-id: ${{ steps.fc.outputs.comment-id }}
           issue-number: ${{ github.event.pull_request.number }}
           body: |
-            Doxygen warnings output: (if empty, there are no warnings). Please correct all warnings before merging.
+            Doxygen warnings output: (if empty, there are no warnings). Please correct any warnings before merging.
             ```yaml
               ${{ steps.doxygen-warnings.outputs.warnings }}
             ```
